name: Question
description: Ask a usage question
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before asking, please check the [README](../blob/main/README.md) and
        [Getting Started guide](../blob/main/GETTING-STARTED.md).
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Include a snippet of what you are trying to do if relevant.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: 1.3.0
